name: Build
on:
  push:
    branches:
      - 'main'

jobs:
  label_issue:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact.name: Linux
            artifact.path: bin/Debug-linux/FauxPlanet/FauxPlanet
          - os: windows-latest
            artifact.name: Windows
            artifact.path: bin/Debug-linux/FauxPlanet/FauxPlanet.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: abel0b/setup-premake@v2.4
        with:
          version: "5.0.0-beta2"
      - name: Generate make files
        run: |
          premake5 gmake2
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact.name }}
          path: ${{ matrix.artifact.path }}
