name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'eng/include'
          - 'eng/src'
          - 'faux_planet/src'
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path }}